"""mudando date para string

Revision ID: 47b830c45b58
Revises: deaaa521e2be
Create Date: 2025-12-01 21:38:16.920022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b830c45b58'
down_revision = 'deaaa521e2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_seguranca', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('area_atuacao',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('solicitacao_transporte', schema=None) as batch_op:
        batch_op.alter_column('data_saida',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('data_retorno',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_transporte', schema=None) as batch_op:
        batch_op.alter_column('data_retorno',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('data_saida',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('solicitacao_seguranca', schema=None) as batch_op:
        batch_op.alter_column('area_atuacao',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('data_inicio',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
