"""empty message

Revision ID: 5e647727ed64
Revises: 639d28898105
Create Date: 2025-11-26 22:25:39.853003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e647727ed64'
down_revision = '639d28898105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(length=50), nullable=True),
    sa.Column('ambiente', sa.String(length=100), nullable=True),
    sa.Column('frequencia', sa.String(length=50), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('area_atuacao', sa.String(length=100), nullable=True),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('frequencia', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_veiculo', sa.String(length=60), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_passageiros', sa.Integer(), nullable=True),
    sa.Column('quantidade_onibus', sa.Integer(), nullable=True),
    sa.Column('preco_diaria', sa.Float(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('horario_saida', sa.Time(), nullable=True),
    sa.Column('horario_chegada', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_transporte')
    op.drop_table('service_seguranca')
    op.drop_table('service_limpeza')
    op.drop_table('services')
    # ### end Alembic commands ###
