"""empty message

Revision ID: 639d28898105
Revises: 6cb7b2e960b9
Create Date: 2025-11-18 22:04:25.810303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d28898105'
down_revision = '6cb7b2e960b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_perfil', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imagem_perfil')

    # ### end Alembic commands ###
