"""init atualizacao do banco

Revision ID: 6cb7b2e960b9
Revises: 
Create Date: 2025-11-18 21:40:57.029393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb7b2e960b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('unidade_medida_id', sa.Integer(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_produto.id'], ),
    sa.ForeignKeyConstraint(['unidade_medida_id'], ['unidade_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('user')
    op.drop_table('unidade_medida')
    op.drop_table('tipo_produto')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
