"""models solicitação

Revision ID: 8f5a1e5daf49
Revises: fef31e63b975
Create Date: 2025-12-01 20:48:23.552508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5a1e5daf49'
down_revision = 'fef31e63b975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(), nullable=True),
    sa.Column('amibente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('area_atuacao', sa.Date(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('quantidade_de_onibus', sa.Integer(), nullable=True),
    sa.Column('horario_de_saida', sa.String(), nullable=True),
    sa.Column('horario_de_chegada', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_transporte')
    op.drop_table('solicitacao_seguranca')
    op.drop_table('solicitacao_limpeza')
    # ### end Alembic commands ###
