"""empty message

Revision ID: ab88f9b34cbe
Revises: 1fea1aa53f7f
Create Date: 2025-11-28 20:22:06.573794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab88f9b34cbe'
down_revision = '1fea1aa53f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_seguranca')
    op.drop_table('service_limpeza')
    with op.batch_alter_table('service_transporte', schema=None) as batch_op:
        batch_op.drop_column('quantidade_onibus')
        batch_op.drop_column('horario_chegada')
        batch_op.drop_column('horario_saida')
        batch_op.drop_column('data_retorno')
        batch_op.drop_column('data_saida')
        batch_op.drop_column('capacidade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_transporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_saida', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_retorno', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('horario_saida', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('horario_chegada', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_onibus', sa.INTEGER(), nullable=True))

    op.create_table('service_limpeza',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('tempo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ambiente', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frequencia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('periodo', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_seguranca',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('area_atuacao', sa.VARCHAR(length=100), nullable=True),
    sa.Column('turno', sa.VARCHAR(length=50), nullable=True),
    sa.Column('frequencia', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
