"""new col

Revision ID: b03c797c2a23
Revises: 
Create Date: 2025-12-02 20:00:59.970634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03c797c2a23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('imagem_perfil', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('unidade_medida_id', sa.Integer(), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_produto.id'], ),
    sa.ForeignKeyConstraint(['unidade_medida_id'], ['unidade_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_limpeza', sa.String(length=60), nullable=True),
    sa.Column('tamanho_area', sa.Float(), nullable=True),
    sa.Column('frequencia', sa.String(length=60), nullable=True),
    sa.Column('produtos_incluidos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_seguranca', sa.String(length=60), nullable=True),
    sa.Column('quantidade_vigilantes', sa.Integer(), nullable=True),
    sa.Column('horas_atuacao', sa.Integer(), nullable=True),
    sa.Column('rondas_por_turno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_veiculo', sa.String(length=60), nullable=True),
    sa.Column('quantidade_passageiros', sa.Integer(), nullable=True),
    sa.Column('preco_diaria', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(), nullable=True),
    sa.Column('ambiente', sa.String(), nullable=True),
    sa.Column('frequencia', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.String(), nullable=True),
    sa.Column('area_atuacao', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=200), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_saida', sa.String(), nullable=True),
    sa.Column('data_retorno', sa.String(), nullable=True),
    sa.Column('quantidade_de_onibus', sa.Integer(), nullable=True),
    sa.Column('horario_de_saida', sa.String(), nullable=True),
    sa.Column('horario_de_chegada', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('data_limite', sa.Date(), nullable=True),
    sa.Column('finalidade', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao')
    op.drop_table('solicitacao_transporte')
    op.drop_table('solicitacao_seguranca')
    op.drop_table('solicitacao_limpeza')
    op.drop_table('service_transporte')
    op.drop_table('service_seguranca')
    op.drop_table('service_limpeza')
    op.drop_table('produto')
    op.drop_table('user')
    op.drop_table('unidade_medida')
    op.drop_table('tipo_veiculo')
    op.drop_table('tipo_produto')
    op.drop_table('services')
    op.drop_table('fornecedor')
    op.drop_table('disciplina')
    # ### end Alembic commands ###
