"""create tipo_veiculo table

Revision ID: da690a1cda4d
Revises: a1a6caec0754
Create Date: 2025-11-27 20:49:43.488763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da690a1cda4d'
down_revision = 'a1a6caec0754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_veiculo')
    # ### end Alembic commands ###
