"""solicitação improving


Revision ID: deaaa521e2be
Revises: 8f5a1e5daf49
Create Date: 2025-12-01 21:31:33.197192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaaa521e2be'
down_revision = '8f5a1e5daf49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_limpeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_limpeza', sa.String(length=60), nullable=True),
    sa.Column('tamanho_area', sa.Float(), nullable=True),
    sa.Column('frequencia', sa.String(length=60), nullable=True),
    sa.Column('produtos_incluidos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('tipo_seguranca', sa.String(length=60), nullable=True),
    sa.Column('quantidade_vigilantes', sa.Integer(), nullable=True),
    sa.Column('horas_atuacao', sa.Integer(), nullable=True),
    sa.Column('rondas_por_turno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacao_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ambiente', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('frequencia', sa.String(), nullable=True))
        batch_op.drop_column('amibente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_limpeza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amibente', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('frequencia')
        batch_op.drop_column('ambiente')

    op.drop_table('service_seguranca')
    op.drop_table('service_limpeza')
    # ### end Alembic commands ###
